a2m_model:
  out_dim: 1404
  latent_dim: 512
  model_path: ./pretrained_model/wav2vec2-base-960h
  only_last_fetures: True
  from_pretrained: True

a2p_model:
  out_dim: 6 
  latent_dim: 512
  model_path: ./pretrained_model/wav2vec2-base-960h
  only_last_fetures: True
  from_pretrained: True

pretrained_model:
  a2m_ckpt: ./pretrained_model/audio2mesh.pt
  a2p_ckpt: ./pretrained_model/audio2pose.pt
