pretrained_base_model_path: './pretrained_models/stable-diffusion-v1-5'

image_encoder_path: './pretrained_aniportrait/image_encoder'
pretrained_vae_path: './pretrained_aniportrait/sd-vae-ft-mse'
denoising_unet_path: "./pretrained_aniportrait/denoising_unet.pth"
reference_unet_path: "./pretrained_aniportrait/reference_unet.pth"
pose_guider_path: "./pretrained_aniportrait/pose_guider.pth"
motion_module_path: "./pretrained_aniportrait/motion_module.pth"

frame_interpolation_model_path: "./pretrained_aniportrait/film_net_fp16.pt"

audio_inference_config: "./configs/inference/aniportrait/inference_audio.yaml"
inference_config: "./configs/inference/aniportrait/inference_v2.yaml"
weight_dtype: 'fp16'

# path of your custom head pose template
# pose_temp: "./configs/inference/head_pose_temp/pose_temp.npy"

#### needs to be modified for new input
test_cases:
  # "examples/reference_images/Screenshot 2024-10-17 at 12.08.54 PM.png":
  #   - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-17 at 12.09.34 PM.png":
    - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-17 at 12.09.53 PM.png":
    - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-17 at 12.10.43 PM.png":
    - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-17 at 1.38.56 PM.png":
    - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-17 at 1.48.52 PM.png":
    - "examples/driving_audios/1.wav"
  "examples/reference_images/Screenshot 2024-10-21 at 12.03.48 PM.png":
    - "examples/driving_audios/1.wav"
